# Site settings
title: Dart
description: >-
  Dart is a client-optimized language for developing fast apps on any platform.
url: https://dart.cn
dev-url: https://debug.dart.cn
repo:
  this: https://github.com/cfug/dart.cn
  shared: https://github.com/dart-lang/site-shared
branch: main
port: 4000
source: src

strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
future: true # In support of https://github.com/dart-lang/site-www/issues/1111
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - ../node_modules/bootstrap-scss
plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 3
  no_toc_section_class: no_toc_section


dart-site: ''
flutter: https://flutter.cn
flutter-docs: https://flutter.cn/docs
dart_api: https://api.dart.cn # temporary keep for .cn site to see if there is any refrence to it
flutter_api: https://api.flutter-io.cn # temporary keep for .cn site to see if there is any refrence to it
pub: https://pub.flutter-io.cn
pub-api: https://pub.flutter-io.cn/documentation
pub-pkg: https://pub.flutter-io.cn/packages
dartpad: https://dartpad.cn
dart-api: https://api.dart.cn
flutter-api: https://api.flutter-io.cn
news: https://news.dartlang.org
announce: https://groups.google.com/a/dartlang.org/g/announce

show_banner: true

defaults:
- scope:
    path: ''
    # type: pages
  values:
    layout: default
    toc: true

custom:
  downloads:
    dartarchive-be-url-prefix: https://storage.flutter-io.cn/dart-archive/channels/be/raw
    dartarchive-dev-url-prefix: https://storage.flutter-io.cn/dart-archive/channels/dev/release
    dartarchive-stable-url-prefix: https://storage.flutter-io.cn/dart-archive/channels/stable/release
    binaries:
      - os: windows
        name: Windows
        ext: zip
        editor-ext: zip
      - os: macos
        name: Mac
        ext: zip
        editor-ext: zip
      - os: linux
        name: Linux
        ext: zip
        editor-ext: zip


# `symlinked-sources` can refer to individual files or directories
# under `src` that are symlinked to somewhere outside `src`, or it can
# refer to the root folder of the symlinked content (like `site-shared/src`):
# symlinked-sources: [site-shared/src]

# Increment this global og:image URL version number (used as a query parameter)
# when you update any og:image file. (Also increment the corresponding number
# in the `firebase.json` redirect rule.)
og_image_vers: "?2"


## Site-wide shorthands

alert:
  important: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">error</i> **重要说明:**
  info: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">info</i>
  note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">info</i> **备注:**
  flutter-note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <img src="/assets/img/shared/flutter/icon/64.png" width="24" alt="Flutter logo"> **与 Flutter 相关的备注:**
  version-note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">merge_type</i> **版本提示:**
  secondary: >-
    <aside class="alert alert-secondary" role="alert" markdown="1">
  tip: >-
    <aside class="alert alert-success" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">tips_and_updates</i> **小提示:**
  warn: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">report_problem</i>
  warning: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">report_problem</i> **请注意:**
  end: </aside>

why:
  learn: >-
    <div class="mini-toc" markdown="1">
      <h4 class="no_toc">你将会学习:</h4>
  end: </div>
