name: Compile Archive JS

on:
  push:
    branches:
      - main
    paths:
      - "**/download_archive.*"

permissions:
  contents: write

jobs:
  compile_archive_js:
    if: ${{ github.actor.login != 'cfug-dev' &&
            github.repository == 'cfug/dart.cn' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.CFUG_DEV_TOKEN }}
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      - name: Build Dart archives downloading JS
        run: >
          bash tool/get-dart/archive/compile.sh
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CFUG_DEV_TOKEN }}
          base: main
          branch: bot/update-download-archive-dart-js
          add-paths: |
            ./src/content/assets/js/get-dart/download_archive.*
          title: '[🤖bot] Update: download_archive'
          body: 'GitHub Action: [.github/workflows/compile_archive_js.yml](https://github.com/cfug/dart.cn/blob/main/.github/workflows/compile_archive_js.yml)'
          committer: 'cfug-dev <cfug-dev@googlegroups.com>'
          commit-message: '[🤖bot] Update: download_archive'
          branch-suffix: timestamp
          labels: |
            auto.PR
